### ISSUE TITLE
Sharing location on toolbar - Anirudh

### ISSUE THREAD

**Issue by swethadevireddy** [codepath-2016-group5/FindMate#12]
share location swipe yes/No  , if yes

share all -> yes 
if no 
show friends list and can select from friend list.

**Comment by apadmarao** [comment]
Implemented switch in toolbar to enable / disable location sharing. 

Their is no access control right now - location will be shared with all friends. Long-term, I think we should go with the concept of groups, e.g. "family" and enable or disable sharing per group.
