### ISSUE TITLE
Show - get  the shared prefrences from db and show it on Map (mahesh)

### ISSUE THREAD

**Issue by swethadevireddy** [codepath-2016-group5/FindMate#13]

**Comment by apadmarao** [comment]
@mdathrika 
You'll have to use polling, or parse livequery:
https://github.com/ParsePlatform/parse-server/wiki/Parse-LiveQuery
https://github.com/TGIO/ParseLiveQuery

to get all of the user's in the currently selected group, and then display them on the map.
